name: Build and Tag Release

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0 # Fetches all history & tags automatically

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js & Cache
      uses: actions/setup-node@v7
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Check if current package version is already tagged
      id: check-version
      run: |
        PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

        if git rev-parse "$PACKAGE_VERSION" >/dev/null 2>&1; then
          echo "Version $PACKAGE_VERSION already tagged. Skipping build."
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "New version detected ($PACKAGE_VERSION). Proceeding with build."
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies
      if: steps.check-version.outputs.skip != 'true'
      run: pnpm install --frozen-lockfile

    - name: Build
      if: steps.check-version.outputs.skip != 'true'
      run: pnpm run build:release

    - name: Commit dist folder and push tag
      if: steps.check-version.outputs.skip != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/*.js
        git commit -m "$PACKAGE_VERSION" --no-verify || echo "No changes to commit"
        git tag "$PACKAGE_VERSION"
        git push origin "$PACKAGE_VERSION"
      env:
        HUSKY_SKIP_HOOKS: true